import { z } from 'zod';

/**
 * Form schemas mirroring the server-side validators so a user sees the failure
 * inline instead of as a 400 from the API.
 *
 * Sources of truth:
 *  - `backend/schemas.py`      → UserCreate name/username validators
 *  - `backend/auth/utils.py`   → validate_password_strength
 */

const SPECIAL_CHARS = /[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?`~]/;

/**
 * The backend enforces five rules. Note the web app's register form only checks
 * four — it omits the lowercase rule — so a password like `PASSWORD1!` passes
 * its UI and is then rejected by the API. Mobile checks all five.
 */
export const passwordRules = [
  { key: 'length', label: 'At least 8 characters', test: (v: string) => v.length >= 8 },
  { key: 'upper', label: 'One uppercase letter', test: (v: string) => /[A-Z]/.test(v) },
  { key: 'lower', label: 'One lowercase letter', test: (v: string) => /[a-z]/.test(v) },
  { key: 'digit', label: 'One number', test: (v: string) => /\d/.test(v) },
  { key: 'special', label: 'One special character', test: (v: string) => SPECIAL_CHARS.test(v) },
] as const;

export const passwordSchema = z
  .string()
  .min(8, 'Password must be at least 8 characters long.')
  .refine((v) => /[A-Z]/.test(v), 'Password must contain at least one uppercase letter.')
  .refine((v) => /[a-z]/.test(v), 'Password must contain at least one lowercase letter.')
  .refine((v) => /\d/.test(v), 'Password must contain at least one digit.')
  .refine((v) => SPECIAL_CHARS.test(v), 'Password must contain at least one special character.');

export const loginSchema = z.object({
  /** The backend matches this against either email or username. */
  loginId: z.string().trim().min(1, 'Enter your username or email'),
  password: z.string().min(1, 'Enter your password'),
});

export type LoginForm = z.infer<typeof loginSchema>;

export const registerSchema = z
  .object({
    name: z
      .string()
      .trim()
      .min(2, 'Name must be between 2 and 100 characters')
      .max(100, 'Name must be between 2 and 100 characters'),
    username: z
      .string()
      .trim()
      .min(3, 'Username must be between 3 and 30 characters')
      .max(30, 'Username must be between 3 and 30 characters')
      .regex(/^[a-zA-Z0-9_]+$/, 'Only letters, digits and underscores'),
    email: z.email('Enter a valid email address').trim(),
    password: passwordSchema,
    confirmPassword: z.string(),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: 'Passwords do not match',
    path: ['confirmPassword'],
  });

export type RegisterForm = z.infer<typeof registerSchema>;

export const emailSchema = z.object({
  email: z.email('Enter a valid email address').trim(),
});

export type EmailForm = z.infer<typeof emailSchema>;

export const resetSchema = z
  .object({
    /** Six digits, generated by `random.choices(string.digits, k=6)`. */
    code: z.string().trim().length(6, 'Enter the 6-digit code'),
    password: passwordSchema,
    confirmPassword: z.string(),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: 'Passwords do not match',
    path: ['confirmPassword'],
  });

export type ResetForm = z.infer<typeof resetSchema>;
